# Generated by Django 5.1.3 on 2024-11-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='profile_management.userprofile'),
        ),
    ]
