# Generated by Django 5.1.3 on 2024-11-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='editTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
