# Generated by Django 5.1.3 on 2024-11-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
