# Generated by Django 5.1.3 on 2024-11-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
